name: Overwritten Artifact Bug

permissions:
  contents: read

on: [push, workflow_dispatch]

env:
  GH_TELEMETRY: false

jobs:

  upload_v1:
    runs-on: &RUNNER ubuntu-26.04
    steps:
      - run: echo VERSION=v1 >>"${GITHUB_ENV}"
      - &CREATE
        run: |
          echo ${{ github.sha }} ${{ env.VERSION }} >version.txt
      - &UPLOAD
        uses: $/.github/actions/upload-artifacts
        with:
          patterns: |
            *.txt
    
  upload_v2:
    needs: upload_v1
    runs-on: *RUNNER
    steps:
      - run: echo VERSION=v2 >>"${GITHUB_ENV}"
      - *CREATE
      # - run: sleep $((60 * 3))
      - *UPLOAD

  download:
    needs: upload_v2
    runs-on: *RUNNER
    steps:
      - uses: $/.github/actions/download-artifacts
        with:
          regex: \.txt$
      - run: |
          ls
          echo "::notice::sha256=$(sha256sum *.txt): $(cat *.txt)"

