name: Overwritten Artifact Bug

permissions:
  contents: read

on: [push, workflow_dispatch]

env:
  GH_TELEMETRY: false

jobs:

  upload_v1:
    runs-on: &RUNNER ubuntu-26.04
    env:
      VERSION: v1
    steps:
      - run: echo VERSION=v1 >>"${GITHUB_ENV}"
      - &CREATE
        run: |
          echo ${{ github.sha }} ${{ env.VERSION }} >version.txt
          zip artifact.zip version.txt
          echo "::notice::artifact.zip sha256: $(sha256sum artifact.zip)"
      - &UPLOAD
        uses: actions/upload-artifact@v7.0.1
        with:
          archive: false
          path: artifact.zip
          overwrite: true

  upload_v2:
    needs: upload_v1
    runs-on: *RUNNER
    steps:
      - run: echo VERSION=v2 >>"${GITHUB_ENV}"
      - *CREATE
      - *UPLOAD

  download:
    needs: upload_v2
    runs-on: *RUNNER
    steps:
      - uses: actions/download-artifact@v8.0.1
        with:
          merge-multiple: true
          skip-decompress: true
      - run: |
          ls
          sha256sum *
          echo "::notice::artifact.zip sha256: $(sha256sum artifact.zip)"

